### ISSUE TITLE
Slight lag while registering new entry

### ISSUE THREAD

**Issue by sidhanshumonga** [hispindia/hi-android-tracker-capture#1]
Hi there, 
I am facing lags while registering new patient. Text boxes, drop-downs and date-boxes are responding with slight delay.

**Comment by nhancv** [comment]
Make sure you build on "develop" branch at latest commit.
Please take a screenshot, it's very helpful for me to detect what stage you are facing.

**Comment by sidhanshumonga** [comment]
Well, I am not facing any lag anymore, but still I'm facing issue of organisation units, issue no. #2 .

**Comment by nhancv** [comment]
please check it again.

**Comment by sidhanshumonga** [comment]
Yeah, It's working now, thanks.
