### ISSUE TITLE
Error in syncing data

### ISSUE THREAD

**Issue by sidhanshumonga** [hispindia/hi-android-tracker-capture#3]
![2723484959268495766-account_id 1](https://user-images.githubusercontent.com/24932914/27852677-b2c64d8a-617d-11e7-87de-a0268fdec2e8.png)
Hi there,

I am getting exception error while syncing data to server. So I am unable to register any new patient, and test for any further stage as enrollment is not syncing.

**Comment by nhancv** [comment]
Please test it again, and make sure you build on "develop" branch at latest commit.
