### ISSUE TITLE
To Support Data Type Tracker Associate!

### ISSUE THREAD

**Issue by i-sourabh** [hispindia/hi-android-tracker-capture#6]
Need to support dataelements of type Tracker Associate!

Tracker associate value type is used to store UID of a tracked entity
instance. The intention is to link two tracked entity instances.

**Comment by nhancv** [comment]
need more information to clear requirement

**Comment by harsh-a1** [comment]
Tracker Associate is a value type of (TEA)tracked entity attributes (just like Numeric, Text, Date etc...)

It is used to link two Tracked entity Instances in a very simplistic way. If a TEA has value type of tracker associate then the value which it will have will be the 11 digit uid of another tracked entity instance in the system.

I will share the credentials of one of our instances to you on mail. There you can see in the household members program where we have used it.

**Comment by nhancv** [comment]
Updated
