### ISSUE TITLE
Unable to search through a dropdown list

### ISSUE THREAD

**Issue by sidhanshumonga** [hispindia/hi-android-tracker-capture#7]
Hi nhan,

I was testing the Application on INTPART instance, I faced an issue in the app. Under PHC25, and household program, I was entering data. There at dropdown list of household members, 

1. - I was unable to search through the list, I would like to search through numbers, to be specific. 
2. - Also, Whenever I delete a letter, I mean after pressing backspace even for once, Searching was like disabled.

**Comment by nhancv** [comment]
I've detected the testing device with build at [b5983f6] commit which not latest, please check at yours. Make sure build at latest commit. For easier to tracking, tell me the app version (Go to settings -> app -> app info). With the search view, search input will show if number of items > 5
Better for me if you attach your screenshot.
